### ISSUE TITLE
app.router is deprecated in Express 4

### ISSUE THREAD

**Issue by Tamfoolery** [alubbe/named-routes#5]
I'm getting this error with Express 4:

```console
Error: 'app.router' is deprecated!
Please see the 3.x to 4.x migration guide for details on how to update your app.
    at EventEmitter.Object.defineProperty.get (/app/node_modules/express/lib/application.js:120:13)
    at EventEmitter.app.(anonymous function) (/app/node_modules/named-routes/router.js:293:43)
    at Object.<anonymous> (/app/app.js:158:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

My code (basically the same as in the docs)
```javascript
var Router = require('named-routes');
var router = new Router();
router.extendExpress(app);
router.registerAppHelpers(app);

app.get('/', 'builds.index', function (req, res, next) { builds.index(req, res, next, db); });
```

Is this something I'm doing wrong, or is it a just compatibility issue with Express 4?

**Comment by alubbe** [comment]
You should try to use ```router.extendExpress4(app)```. Let me know if that fixes it.

**Comment by alubbe** [comment]
2.0.0 is now released, specifically for express 4!
